### PR TITLE
**DRAFT** Heltec 32 V3

### PR DESCRIPTION
**Pull request by u01-rn**
The Heltec 32 V3 is the successor to the Heltec 32 V2 and any attempts to purchase the V2 result in getting the V3. It is one of the most common LoRa boards used by Meshtastic users due to its price. Getting it to work with RNode-Firmware would make building an RNode in the United States or migration from Meshtastic to Reticulum significantly easier.

This is a DRAFT pull request to create a build for the Heltec 32 V3. 
I have gotten rnode-firmware to successfully:

- compile (w/ESP32S3+SX1262)
- use the LCD on the Heltec 32 V3

This firmware does not boot yet. Any help getting it to boot would be appreciated.

### CODE REVIEW

**Comment by jacobeva** [comment]
I apologise for the nRF specific functions and definitions slipping in there, I should've realised that there would be more SX1262 boards being used than just the nRF ones!

**Comment by markqvist** [comment]
No worries about that @jacobeva!

Thanks for looking into this @u01-rn! Let's just consider this PR experimental for now. Before we get to looking at this, I need to verify functionality of the SX1262 driver on boards types that are already supported. When that is verified, I'll be happy to help out getting this one supported, but to not muddy things up or make it too complex, let's do one thing at a time :)

**Comment by u01-rn** [comment]
Sounds great. I look forward to it.

For future reference:
I have the physical hardware and am willing to test images and functionality.

**Comment by n4ijk** [comment]
Just wanted to see how I could help in getting the V3 supported? I'm happy to donate a board / etc to get this going. These are such handy little boards and they are very cheap!

**Comment by markqvist** [comment]
The SX1262 driver is verified and working well. There's already SX1262 based builds in the releases now :)

For anyone wanting to give Heltec V3 compatibility a shot, it the easiest approach is probably to base it off of the `firmware-t3s3` build target, which works on the LilyGo T3-S3 boards, based on the ESP32-S3 MCU. This ESP32 variant is slightly different, and Bluetooth support is not implemented yet, but other than that, it does work very well.

Since the Heltec V3 seems to be very close to the LilyGO T3-S3, it should be pretty easy to get at least a basic build up and running like this.

**Comment by n4ijk** [comment]
I'll try to give this a shot tonight - thank you!

-------- Original Message --------

**Comment by n4ijk** [comment]
I think I'm going to need to play with it a bit more to get it to go, running the T3-S3 didn't work on it at all.

**Comment by cobraPA** [comment]
Ah, I missed this was in progress.  I've submitted the version I was working on as a PR as well, which I pulled from the iOS work I have been doing.  Boot and display are working there, and serial connection should be also.  No Bluetooth yet.

**Comment by markqvist** [comment]
It's fine you added a new PR, I'm not sure what the state of this one was, after we changed a lot of stuff around during the other SX126x work. Thanks!

**Comment by markqvist** [comment]
Since Heltec V3 support has now been added to the firmware, along with all the other recent changes, I'll close this draft PR.

**Pull request closed without merging**
